public class IMSIssuanceSettings
{
    public int CacheExpirationMinutes { get; set; } = 60;
    public IssuanceEngineSettings EngineSettings { get; set; }
    public DocumentSettings DocumentSettings { get; set; }
    public PaymentSettings PaymentSettings { get; set; }
    public ValidationSettings ValidationSettings { get; set; }
    public WorkflowSettings WorkflowSettings { get; set; }
    public RetryPolicy RetryPolicy { get; set; }
}

public class IssuanceEngineSettings
{
    public bool EnableParallelProcessing { get; set; } = true;
    public int MaxConcurrentIssuance { get; set; } = 5;
    public int IssuanceTimeoutSeconds { get; set; } = 300;
    public bool RequirePaymentBeforeIssuance { get; set; } = true;
    public bool AutoGenerateDocuments { get; set; } = true;
    public List<string> RequiredDocuments { get; set; }
    public Dictionary<string, string> DocumentTemplates { get; set; }
}

public class DocumentSettings
{
    public bool CompressDocuments { get; set; } = true;
    public string StoragePath { get; set; }
    public List<string> RequiredSignatures { get; set; }
    public Dictionary<string, string> SignatureRequirements { get; set; }
    public int DocumentRetentionDays { get; set; } = 90;
    public List<string> AllowedFileTypes { get; set; }
}

public class PaymentSettings
{
    public List<string> AcceptedPaymentMethods { get; set; }
    public bool RequirePaymentVerification { get; set; } = true;
    public decimal MinimumDownPayment { get; set; }
    public List<string> AvailablePaymentPlans { get; set; }
    public Dictionary<string, decimal> PaymentPlanFees { get; set; }
    public bool AllowAutomaticPayments { get; set; } = true;
}

public class ValidationSettings
{
    public bool StrictValidation { get; set; } = true;
    public List<string> RequiredFields { get; set; }
    public Dictionary<string, ValidationRule> CustomValidationRules { get; set; }
    public bool ValidateAddresses { get; set; } = true;
    public bool ValidatePaymentInfo { get; set; } = true;
    public int MaxRetryAttempts { get; set; } = 3;
}

public class WorkflowSettings
{
    public bool EnableWorkflowEngine { get; set; } = true;
    public List<string> RequiredSteps { get; set; }
    public Dictionary<string, WorkflowStep> CustomSteps { get; set; }
    public bool AllowParallelSteps { get; set; } = false;
    public int StepTimeoutSeconds { get; set; } = 60;
    public List<string> AutoApprovalCriteria { get; set; }
}

public class WorkflowStep
{
    public string Name { get; set; }
    public string Description { get; set; }
    public List<string> RequiredRoles { get; set; }
    public List<string> DependentSteps { get; set; }
    public bool IsOptional { get; set; }
    public int Order { get; set; }
} 